# Generated by Django 4.2 on 2023-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("user_id", models.IntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DOC", "DOC"),
                            ("PDF", "PDF"),
                            ("CSV", "CSV"),
                            ("WEB", "WEB"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("date", models.CharField(max_length=20)),
                ("topic", models.CharField(max_length=100)),
            ],
        ),
    ]
