# Generated by Django 4.2 on 2023-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
