# Generated by Django 4.2 on 2023-07-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_username_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DOC", "DOC"),
                            ("PDF", "PDF"),
                            ("CSV", "CSV"),
                            ("WEB", "WEB"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("date", models.CharField(max_length=20)),
                ("topic", models.CharField(max_length=100)),
            ],
        ),
    ]
