# Generated by Django 4.2 on 2023-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.CharField(default="sdfsdf", max_length=50),
            preserve_default=False,
        ),
    ]
